name: lidar_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pdal=2.8.4
  - python-pdal
  - gdal
  - untwine
  - geopandas
  - pandas
  - numpy
  - proj
  - proj-data
  - pyproj
  - laspy
  - tqdm
  - psutil
